/**
 * This test is used to manually verify the leaf set update mechanism
 * is working correctly. The node_id of a node is just its index.
 * After all nodes joins, it will wait for 20 seconds then node 10
 * will exit. Soon you will see messages like "Fail to send exchange
 * message from x to <pid of node 10>" in stderr. But it should stop
 * after 2 seconds. After that, the trace file should be used to manually
 * verify node 8, 9, 11, 12's leaf set is updated to remove node 10.
 */
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>

#include <rednet.h>
#include <rednet-p2p.h>

nodeID Nid;
int Idx;

int
main(int argc, char **argv) {
    int status;

    if (argc < 2) {
        fprintf(stderr,
                "Process index argument missing: run with ## on command line.\n");
        exit(1);
    }

    Idx = atoi(argv[1]);    /* number from 0 to 31 */
    // Nid = GetNodeID();
    Nid = Idx;

    fprintf(stderr, "Pid %d nodeID %04x index %d\n", GetPid(), Nid, Idx);

    /*
     *  As noted above, each of the 32 computers generated by -N starts
     *  up immediately, with the kernel (system) process running.  But
     *  the user process on each starts at a time randomly spread
     *  over the first 20 seconds of execution.  We do the Join()
     *  right away, since the kernel on all of the computers should be
     *  up and running now and thus able to participate in message
     *  forwarding including an expanding ring search.
     */
    if (Idx != 0) {
        fprintf(stderr, "Process Idx %d is sleeping before Join\n", Idx);
        MilliSleep(25 * 1000);
    }
    status = Join(Nid);
    if (status != 0) {
        fprintf(stderr, "ERROR: Join returned %d!\n", status);
        exit(1);
    }
    if (Idx == 0) {
        fprintf(stderr, "Process Idx %d is sleeping after Join\n", Idx);
        MilliSleep(1000 * 1000);
    }

    fprintf(stderr, "leaf set should be static now\n");
    if (Idx != 10) {
        MilliSleep(1000 * 1000); // for easy debug
    }

    if (Idx == 10) {
        MilliSleep(20 * 1000); // for easy debug
        fprintf(stderr, "Process Idx %d is exiting\n", Idx);
    }

    exit(0);
}
